apiVersion: v2
name: flask-app
description: A Helm chart for Flask application with Promtail sidecar
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - flask
  - promtail
  - logging
maintainers:
  - name: Eduard Constantinescu
    email: eduard.constantinescu98@gmail.com